language: node_js
node_js:
 - 6

install:
 - npm install
 - curl https://login.taobao.com/member/login.jhtml?style=mini&from=alimama&redirectURL=http%3A%2F%2Flogin.taobao.com%2Fmember%2Ftaobaoke%2Flogin.htm%3Fis_login%3d1&full_redirect=true&disableQuickLogin=true

before_deploy:
 - npm run dist.min
