language: node_js
node_js:
 - 6

install:
 - npm install
 - mkdir cache
 - mkdir error

after_script:
 - ls -al cache
 - ls -al error

deploy:
 provider: releases
 user: $user
 password: $password
 file: 
  - "cache/phan.log"
  - "error/1.jpg"
 skip_cleanup: true
